# Machine Learning Example

## Load Data

function >> Class >> Module >> Library (Framework)

Sklearn (Libraray) [Main Folder] >> Subfolders  >> Modules >> Classes

In [7]:
import sklearn

data = sklearn.datasets.load_iris()

In [8]:
from sklearn import datasets

data = datasets.load_iris()

In [11]:
from sklearn.datasets import load_iris

data = load_iris()

In [14]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [15]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Data Splitting

In [21]:
features = data['data']
target = data['target'].reshape(-1,1)

In [22]:
features.shape

(150, 4)

In [23]:
target.shape

(150, 1)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target)

## Modelling

In [28]:
# Linear Regression
from sklearn.linear_model import LinearRegression    # import Class (blueprint)
reg_model1 = LinearRegression()                      # Make an instance (copy)
reg_model2 = LinearRegression()
reg_model3 = LinearRegression()

In [30]:
reg_model1.fit(X_train, y_train)                           # Fitting Method

LinearRegression()

In [32]:
# reg_model1.predict(X_test)                                 # Prediction Method

In [33]:
reg_model1.score(X_test, y_test)                           # Scoring Method

0.9108339388677439

In [34]:
reg_model1.coef_            # Attribute

array([[-0.02613136, -0.03567866,  0.19188465,  0.60319818]])

```
Class LinearRegression():
    def __init__(self):
        pass
        
    def fit(self, X_train, y_train):
        pass
        
    def predict(self, X_test):
        pass
        
    def score(self, X_test, y_test):
        pass```

In [35]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
reg2 = DecisionTreeRegressor()

reg2.fit(X_train, y_train)                       # Fitting Method  (Different Behavior)
reg2.predict(X_test)                             # Prediction Method  (Different Behavior)
reg2.score(X_test, y_test)                       # Scoring Method  (Different Behavior)

0.8788522848034006

In [36]:
reg2.feature_importances_           # Attribute

array([0.        , 0.01557224, 0.77913567, 0.20529209])

``` 
Class DecisionTreeRegressor():
    def __init__(self):
        pass
        
    def fit(self, X_train, y_train):
        pass
        
    def predict(self, X_test):
        pass
        
    def score(self, X_test, y_test):
        pass```

# OOP Principles
1. *Abstraction:*
> Hide unnecessary details from user
2. *Encapsulation:*
> Combine Attributes and Methods
3. *Polymorphism:*
> Many Functions with the same name, but different beahviour
4. *Inheritence:*
> Create new classes from existing classes

```
from sklearn.linear_model import LinearRegression
Class MyLinearRegression(LinearRegression):
    def __init__(self):
        pass
        
    def fit(self, X_train, y_train):
        pass
        
    def predict(self, X_test):
        pass
        
    def score(self, X_test, y_test):
        pass```